# docker-compose.yml
version: '3'
services:
  twap:
    restart: always
    image: twap
    build: .
    env_file:
      - ./.env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: 10m
    volumes:
      - ./logs:/app/logs
